### ISSUE TITLE
[Question] How do you know which spray bit is which?

### ISSUE THREAD

**Issue by Timmiej93** [baleBaron/FS17_ManureMod#3]
Hi, 

I've been using your manure mod for a while now, and I really like it. I'd like to know how you determined that manure is spray bit 2, as you state [here](https://github.com/baleBaron/FS17_ManureMod/blob/master/manureMod.lua#L17). I've been trying to figure this out, but I simply can't find a way to determine which spray bit this would be.
I hope you can help me out with this.

Tim

**Comment by baleBaron** [comment]
Through trial and error I suppose.
Print the value of g_currentMission.sprayNumChannels, have a look at the groundShader.xml and also have a look at the processSprayerAreas (https://gdn.giants-software.com/documentation_scripting.php?version=script&category=70&class=3514#processSprayerAreas47546)

It makes sense that manure is spray bit 2 (brown) and the others are spray bit 1 (darker), since there are only 2 different types of visible fertilization layers.

And in the end it checks out, writing bit 1 sets darker layer, bit 2 brown.
Sorry I can't give a better answer than this, but often we have to figure stuff out this way.

**Comment by Timmiej93** [comment]
Thank you for your reply, much appreciated!
